# Generated by Django 5.2.7 on 2025-10-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagueapp', '0003_posts_tags_alter_postsimages_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='title',
        ),
    ]
