# Generated by Django 5.2.7 on 2025-10-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueapp', '0005_alter_postsimages_post_postlikes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default="{% static 'default/profile/avatar/no_photo.jpg'%}", upload_to='images/profiles/avatars'),
        ),
    ]
