# Generated by Django 5.2.7 on 2025-10-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueapp', '0006_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default/profile/avatar/no_photo.jpg', upload_to='images/profiles/avatars'),
        ),
    ]
