# Generated by Django 5.2.7 on 2025-10-13 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueapp', '0007_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsimages',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leagueapp.posts', verbose_name='Пост'),
        ),
    ]
